name: First Github Actions

on:
    workflow_dispatch:
    push: 
        branches:
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4
        
            - name: Get file name
              id: getname
              run: | 
                cd code
                echo "filename=$(basename -s .apk *.apk)" >> $GITHUB_OUTPUT
            
            - name: Test output
              run:  echo ${{ steps.getname.outputs.filename }}
            
            # Publish artifacts
            - uses: actions/upload-artifact@v4
              with:
                name: ${{ steps.getname.outputs.filename }}
                path: code/*.apk
      
    # release:
    #     runs-on: ubuntu-latest

    #     needs: build

    #     steps:
    #       - name: Download artifacts
    #         uses: actions/download-artifact@v4

    #       - name: Zip release
    #         uses: TheDoctor0/zip-release@0.7.5
    #         with:
    #           filename: 'release.zip'

    #       - name: Create Github Release
    #         uses: actions/create-release@v1.1.4
    #         env:
    #           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    #         with:
    #           tag_name: v${{ github.ref }}
    #           release_name: Release ${{ github.ref }}
    #           draft: false
    #           prerelease: true

          

          