name: First Github Actions

on:
    workflow_dispatch:
    push: 
        branches:
            - 'main'

jobs:
    build:
        runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v4
    
        - name: Get file name
          id: getname
          run: | 
            cd code
            echo "filename=$(basename *.apk)" >> $GITHUB_OUTPUT
        
        - name: Test output
          run:  echo ${{ steps.getname.outputs.filename }}